<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SkillSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('skills')->insert([
            ['name' => 'PHP'],
            ['name' => 'JavaScript'],
            ['name' => 'Laravel'],
            ['name' => 'Vue.js'],
            ['name' => 'React'],
            ['name' => 'Node.js'],
            ['name' => 'Python'],
            ['name' => 'Ruby on Rails'],
            ['name' => 'Java'],
            ['name' => 'C#'],
            ['name' => 'Swift'],
            ['name' => 'C++'],
            ['name' => 'TypeScript'],
            ['name' => 'Go'],
            ['name' => 'HTML5'],
            ['name' => 'CSS3'],
            ['name' => 'Sass'],
            ['name' => 'Bootstrap'],
            ['name' => 'Tailwind CSS'],
            ['name' => 'jQuery'],
            ['name' => 'Angular'],
            ['name' => 'Next.js'],
            ['name' => 'React Native'],
            ['name' => 'MySQL'],
            ['name' => 'PostgreSQL'],
            ['name' => 'MongoDB'],
            ['name' => 'SQL'],
            ['name' => 'GraphQL'],
            ['name' => 'RESTful API'],
            ['name' => 'Docker'],
            ['name' => 'Redis'],
            ['name' => 'AWS (Amazon Web Services)'],
            ['name' => 'Firebase'],
            ['name' => 'Heroku'],
            ['name' => 'CI/CD'],
            ['name' => 'Kubernetes'],
            ['name' => 'Jenkins'],
            ['name' => 'Terraform'],
            ['name' => 'Ansible'],
            ['name' => 'GitLab CI'],
            ['name' => 'Azure'],
            ['name' => 'Adobe Photoshop'],
            ['name' => 'Adobe Illustrator'],
            ['name' => 'Sketch'],
            ['name' => 'Figma'],
            ['name' => 'Adobe XD'],
            ['name' => 'UI/UX Design'],
            ['name' => 'Data Analysis'],
            ['name' => 'Data Science'],
            ['name' => 'Machine Learning'],
            ['name' => 'AI (Artificial Intelligence)'],
            ['name' => 'Deep Learning'],
            ['name' => 'Pandas (Python Library)'],
            ['name' => 'R Programming'],
            ['name' => 'Tableau'],
            ['name' => 'Power BI'],
            ['name' => 'Agile'],
            ['name' => 'Scrum'],
            ['name' => 'Trello'],
            ['name' => 'Jira'],
            ['name' => 'Asana'],
            ['name' => 'Confluence'],
            ['name' => 'Basecamp'],
            ['name' => 'Git'],
            ['name' => 'SEO (Search Engine Optimization)'],
            ['name' => 'Digital Marketing'],
            ['name' => 'Content Writing'],
            ['name' => 'Copywriting'],
            ['name' => 'Public Speaking'],
            ['name' => 'Project Management'],
            ['name' => 'Business Analysis'],
            ['name' => 'Product Management'],
            ['name' => 'Spark'],
            ['name' => 'Hive'],
            ['name' => 'Matplotlib (Python Library)'],
            ['name' => 'D3.js'],
            ['name' => 'InVision'],
            ['name' => 'Axure RP'],
            ['name' => 'Marvel App'],
            ['name' => 'SaltStack'],
            ['name' => 'Nagios'],
            ['name' => 'Chef'],
            ['name' => 'Prometheus'],
            ['name' => 'ElasticSearch'],
            ['name' => 'GraphQL'],
            ['name' => 'Apache Kafka'],
            ['name' => 'Foundation'],
            ['name' => 'Ember.js'],
            ['name' => 'Backbone.js'],
            ['name' => 'Rust'],
            ['name' => 'Elixir'],
            ['name' => 'Scala'],
            ['name' => 'Dart'],
            ['name' => 'Kotlin'],
            ['name' => 'Natural Language Processing (NLP)'],
            ['name' => 'Computer Vision'],
            ['name' => 'Reinforcement Learning'],
            ['name' => 'TensorFlow'],
            ['name' => 'PyTorch'],
            ['name' => 'Scikit-Learn'],
            ['name' => 'Keras'],

            // مهارات الإدارة
            ['name' => 'Lean Management'],
            ['name' => 'Business Development'],
            ['name' => 'Financial Analysis'],
            ['name' => 'Supply Chain Management'],
            ['name' => 'Risk Management'],
            ['name' => 'Negotiation Skills'],
            ['name' => 'Operations Management'],

            // مهارات التسويق
            ['name' => 'Social Media Marketing'],
            ['name' => 'Content Strategy'],
            ['name' => 'PPC Advertising'],
            ['name' => 'Email Marketing'],
            ['name' => 'Brand Management'],
            ['name' => 'Influencer Marketing'],
            ['name' => 'Growth Hacking'],

            // الترجمة واللغات
            ['name' => 'English Translation'],
            ['name' => 'Spanish Translation'],
            ['name' => 'French Translation'],
            ['name' => 'German Translation'],
            ['name' => 'Arabic Translation'],
            ['name' => 'Mandarin Chinese'],

            // التعليم والتدريب
            ['name' => 'Instructional Design'],
            ['name' => 'Corporate Training'],
            ['name' => 'Online Course Creation'],
            ['name' => 'Coaching'],
            ['name' => 'Mentoring'],
            ['name' => 'Public Speaking'],

            // الأمان السيبراني
            ['name' => 'Ethical Hacking'],
            ['name' => 'Penetration Testing'],
            ['name' => 'Network Security'],
            ['name' => 'Cryptography'],
            ['name' => 'Blockchain Development'],

            ['name' => 'Blacksmithing'],
            ['name' => 'Carpentry'],
            ['name' => 'Plumbing'],
            ['name' => 'Home Electrical Work'],
            ['name' => 'Painting and Decorating'],
            ['name' => 'Ceramic Installation'],
            ['name' => 'Mobile Phone Repair'],
            ['name' => 'Computer Repair'],
            ['name' => 'Car Maintenance'],
            ['name' => 'Forklift Operation'],
            ['name' => 'Electrical Appliance Repair'],
            ['name' => 'Auto Mechanics'],
            ['name' => 'Tailoring'],
            ['name' => 'Beauty and Makeup'],
            ['name' => 'Floral Design'],
            ['name' => 'Cooking'],
            ['name' => 'Pastry Making'],

            ['name' => 'Sales'],
            ['name' => 'Customer Service'],
            ['name' => 'Warehouse Management'],
            ['name' => 'Customer Relationship Management (CRM)'],
            ['name' => 'Financial Accounting'],
            ['name' => 'Real Estate Marketing'],
            ['name' => 'E-commerce'],


        ]);
    }
}
